import { MaterialInfo, Nutrient } from './types';

export const MOTHER_FERTILIZERS: MaterialInfo[] = [
  {
    id: 'urea',
    name: 'Urea',
    nameTh: 'ยูเรีย',
    chemicalFormula: '(NH₂)₂CO',
    npkDisplay: '46-0-0',
    composition: { [Nutrient.N]: 46 },
    isMotherFertilizer: true,
    description: 'แหล่งไนโตรเจนสูง',
  },
  {
    id: 'ammonium_sulfate',
    name: 'Ammonium Sulfate',
    nameTh: 'แอมโมเนียมซัลเฟต',
    chemicalFormula: '(NH₄)₂SO₄',
    npkDisplay: '21-0-0',
    composition: { [Nutrient.N]: 21, [Nutrient.S]: 24 },
    isMotherFertilizer: true,
    description: 'ให้ไนโตรเจนและกำมะถัน',
  },
  {
    id: 'dap',
    name: 'Diammonium Phosphate (DAP)',
    nameTh: 'ไดแอมโมเนียมฟอสเฟต (แดป)',
    chemicalFormula: '(NH₄)₂HPO₄',
    npkDisplay: '18-46-0',
    composition: { [Nutrient.N]: 18, [Nutrient.P2O5]: 46 },
    isMotherFertilizer: true,
    description: 'แหล่งฟอสฟอรัสสูงและมีไนโตรเจน',
  },
  {
    id: 'map',
    name: 'Monoammonium Phosphate (MAP)',
    nameTh: 'โมโนแอมโมเนียมฟอสเฟต (แมป)',
    chemicalFormula: 'NH₄H₂PO₄',
    npkDisplay: '11-52-0',
    composition: { [Nutrient.N]: 11, [Nutrient.P2O5]: 52 },
    isMotherFertilizer: true,
    description: 'แหล่งฟอสฟอรัสสูงและมีไนโตรเจน',
  },
  {
    id: 'tsp',
    name: 'Triple Superphosphate (TSP)',
    nameTh: 'ทริปเปิลซูเปอร์ฟอสเฟต',
    chemicalFormula: 'Ca(H₂PO₄)₂·H₂O',
    npkDisplay: '0-46-0',
    composition: { [Nutrient.P2O5]: 46, [Nutrient.Ca]: 12 }, // TSP contains Ca
    isMotherFertilizer: true,
    description: 'แหล่งฟอสฟอรัสเข้มข้น',
  },
  {
    id: 'mop',
    name: 'Potassium Chloride (MOP)',
    nameTh: 'โพแทสเซียมคลอไรด์ (มิวเรตออฟโพแทช)',
    chemicalFormula: 'KCl',
    npkDisplay: '0-0-60',
    composition: { [Nutrient.K2O]: 60 },
    isMotherFertilizer: true,
    description: 'แหล่งโพแทสเซียมที่นิยมที่สุด',
  },
  {
    id: 'sop',
    name: 'Potassium Sulfate (SOP)',
    nameTh: 'โพแทสเซียมซัลเฟต',
    chemicalFormula: 'K₂SO₄',
    npkDisplay: '0-0-50',
    composition: { [Nutrient.K2O]: 50, [Nutrient.S]: 18 },
    isMotherFertilizer: true,
    description: 'ให้โพแทสเซียมและกำมะถัน เหมาะสำหรับพืชที่ไวต่อคลอไรด์',
  },
  {
    id: 'potassium_nitrate',
    name: 'Potassium Nitrate',
    nameTh: 'โพแทสเซียมไนเตรต',
    chemicalFormula: 'KNO₃',
    npkDisplay: '13-0-46',
    composition: { [Nutrient.N]: 13, [Nutrient.K2O]: 46 },
    isMotherFertilizer: true,
    description: 'ให้ไนโตรเจนและโพแทสเซียม',
  },
  {
    id: 'calcium_nitrate',
    name: 'Calcium Nitrate',
    nameTh: 'แคลเซียมไนเตรต',
    chemicalFormula: 'Ca(NO₃)₂',
    npkDisplay: '15.5-0-0',
    composition: { [Nutrient.N]: 15.5, [Nutrient.Ca]: 19 },
    isMotherFertilizer: true,
    description: 'ให้ไนโตรเจนและแคลเซียม',
  },
];

export const OTHER_MATERIALS_LIST: MaterialInfo[] = [
  {
    id: 'magnesium_sulfate',
    name: 'Magnesium Sulfate (Epsom Salt)',
    nameTh: 'แมกนีเซียมซัลเฟต (ดีเกลือฝรั่ง)',
    chemicalFormula: 'MgSO₄·7H₂O',
    composition: { [Nutrient.Mg]: 9.8, [Nutrient.S]: 13 },
    isMotherFertilizer: false,
    description: 'แหล่งแมกนีเซียมและกำมะถัน',
  },
  {
    id: 'borax_decahydrate',
    name: 'Borax (Decahydrate)',
    nameTh: 'บอแรกซ์ (ผงกรอบ)',
    chemicalFormula: 'Na₂B₄O₇·10H₂O',
    composition: { [Nutrient.B]: 11.3 },
    isMotherFertilizer: false,
    description: 'แหล่งโบรอน',
  },
  {
    id: 'lime_calcium_carbonate',
    name: 'Lime (Calcium Carbonate)',
    nameTh: 'ปูนขาว (แคลเซียมคาร์บอเนต)',
    chemicalFormula: 'CaCO₃',
    composition: { [Nutrient.Ca]: 39 }, // Approx. 39-40% Ca
    isMotherFertilizer: false,
    description: 'แหล่งแคลเซียม, เพิ่ม pH ดิน',
  },
  {
    id: 'dolomite_lime',
    name: 'Dolomite Lime',
    nameTh: 'ปูนโดโลไมต์',
    chemicalFormula: 'CaMg(CO₃)₂',
    composition: { [Nutrient.Ca]: 21, [Nutrient.Mg]: 11 }, // Approx.
    isMotherFertilizer: false,
    description: 'แหล่งแคลเซียมและแมกนีเซียม, เพิ่ม pH ดิน',
  },
  {
    id: 'gypsum',
    name: 'Gypsum (Calcium Sulfate Dihydrate)',
    nameTh: 'ยิปซัม',
    chemicalFormula: 'CaSO₄·2H₂O',
    composition: { [Nutrient.Ca]: 23, [Nutrient.S]: 18 }, // Approx.
    isMotherFertilizer: false,
    description: 'แหล่งแคลเซียมและกำมะถัน, ไม่กระทบ pH ดินมากนัก',
  },
  {
    id: 'zinc_sulfate_mono',
    name: 'Zinc Sulfate (Monohydrate)',
    nameTh: 'ซิงค์ซัลเฟต (โมโนไฮเดรต)',
    chemicalFormula: 'ZnSO₄·H₂O',
    composition: { [Nutrient.Zn]: 35, [Nutrient.S]: 17 }, // Approx. 35-36% Zn
    isMotherFertilizer: false,
    description: 'แหล่งสังกะสีและกำมะถัน',
  },
];

export const NUTRIENT_LABELS_TH: Record<Nutrient, string> = {
  [Nutrient.N]: "ไนโตรเจน (N)",
  [Nutrient.P2O5]: "ฟอสฟอรัส (P₂O₅)",
  [Nutrient.K2O]: "โพแทสเซียม (K₂O)",
  [Nutrient.Ca]: "แคลเซียม (Ca)",
  [Nutrient.Mg]: "แมกนีเซียม (Mg)",
  [Nutrient.S]: "กำมะถัน (S)",
  [Nutrient.B]: "โบรอน (B)",
  [Nutrient.Zn]: "สังกะสี (Zn)",
};
